[features]
seeds = false

[programs.localnet]
hello_world = "6mi3PrgougeFGizsQmkfga5Z6MnRNa5sbnP8yH7261hN"

[programs.devnet]
hello_world = "6mi3PrgougeFGizsQmkfga5Z6MnRNa5sbnP8yH7261hN"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/home/dev/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
